package commands

import (
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type GenerateContextOptions struct {
	DBPath     string
	KernelName string
	Backend    string
	OutputPath string
	DryRun     bool
}

func GenerateContext(opts GenerateContextOptions) error {
	if opts.DBPath == "" {
		return fmt.Errorf("--db-path is required")
	}
	if opts.KernelName == "" {
		return fmt.Errorf("--kernel-name is required")
	}

	history, err := loadHistory(opts.DBPath)
	if err != nil {
		return fmt.Errorf("failed to load history: %w", err)
	}

	related := findRelatedRuns(history.Runs, opts.KernelName, opts.Backend)
	if len(related) == 0 {
		fmt.Printf("[kernelhub generate-context] no prior runs found for kernel %q\n", opts.KernelName)
		return nil
	}

	doc := buildHistorySummary(opts.KernelName, related)

	if opts.DryRun {
		fmt.Print(doc)
		return nil
	}

	outPath := opts.OutputPath
	if outPath == "" {
		outPath = "history_summary.md"
	}
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(outPath, []byte(doc), 0o644); err != nil {
		return err
	}
	fmt.Printf("[kernelhub generate-context] wrote %s (%d prior run(s), %d total iterations)\n",
		outPath, len(related), countIterations(related))
	return nil
}

// GenerateContextForPrepare is called from Prepare() to auto-inject
// history context into the AKO4ALL context/ directory.
func GenerateContextForPrepare(dbPath, kernelName, backend, contextDir string) error {
	history, err := loadHistory(dbPath)
	if err != nil {
		return err
	}
	related := findRelatedRuns(history.Runs, kernelName, backend)
	if len(related) == 0 {
		return nil
	}

	doc := buildHistorySummary(kernelName, related)
	outPath := filepath.Join(contextDir, "history_summary.md")
	if err := os.WriteFile(outPath, []byte(doc), 0o644); err != nil {
		return err
	}
	fmt.Printf("[kernelhub prepare] injected history context: %d prior run(s), %d iterations -> %s\n",
		len(related), countIterations(related), outPath)
	return nil
}

func findRelatedRuns(runs []RunRecord, kernelName, backend string) []RunRecord {
	normalized := normalizeKernelNameForMatch(kernelName)

	var matched []RunRecord
	for _, run := range runs {
		isRelated := false
		for _, it := range run.Iterations {
			if it.Kernel == "" {
				continue
			}
			itNorm := normalizeKernelNameForMatch(it.Kernel)
			if itNorm == normalized {
				isRelated = true
				break
			}
		}
		if !isRelated {
			continue
		}
		if backend != "" {
			hasBackend := false
			for _, it := range run.Iterations {
				if strings.EqualFold(it.Backend, backend) {
					hasBackend = true
					break
				}
			}
			if !hasBackend {
				continue
			}
		}
		matched = append(matched, run)
	}
	return matched
}

func normalizeKernelNameForMatch(name string) string {
	n := strings.ToLower(name)
	for _, prefix := range []string{"cuda_", "triton_"} {
		n = strings.TrimPrefix(n, prefix)
	}
	for _, suffix := range []string{"_forward", "_backward", "_fwd", "_bwd"} {
		n = strings.TrimSuffix(n, suffix)
	}
	return n
}

type iterationInsight struct {
	RunID     string
	Iteration int
	Subject   string
	Speedup   float64
	Latency   float64
	Changes   string
	Analysis  string
	Correct   bool
}

func buildHistorySummary(kernelName string, runs []RunRecord) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Prior Optimization History: %s\n\n", kernelName))
	b.WriteString("This file is auto-generated by `kernelhub generate-context`.\n")
	b.WriteString("Use these insights to avoid repeating failed experiments and to build on successful strategies.\n\n")

	// Overall stats
	bestSpeedup := 0.0
	bestLatency := math.MaxFloat64
	totalIters := 0
	for _, run := range runs {
		for _, it := range run.Iterations {
			totalIters++
			if it.SpeedupVsBaseline > bestSpeedup {
				bestSpeedup = it.SpeedupVsBaseline
			}
			if it.HasLatency && it.LatencyUs > 0 && it.LatencyUs < bestLatency {
				bestLatency = it.LatencyUs
			}
		}
	}
	if bestLatency == math.MaxFloat64 {
		bestLatency = 0
	}

	b.WriteString("## Summary\n\n")
	b.WriteString(fmt.Sprintf("- **Prior runs**: %d\n", len(runs)))
	b.WriteString(fmt.Sprintf("- **Total iterations**: %d\n", totalIters))
	b.WriteString(fmt.Sprintf("- **Best speedup achieved**: %.2fx\n", bestSpeedup))
	if bestLatency > 0 {
		b.WriteString(fmt.Sprintf("- **Best latency**: %.1f us\n", bestLatency))
	}
	b.WriteString("\n")

	// Collect all meaningful iterations
	var successes []iterationInsight
	var failures []iterationInsight

	for _, run := range runs {
		for _, it := range run.Iterations {
			if it.Changes == "" && it.Analysis == "" {
				continue
			}
			insight := iterationInsight{
				RunID:     run.RunID,
				Iteration: it.Iteration,
				Subject:   it.Subject,
				Speedup:   it.SpeedupVsBaseline,
				Latency:   it.LatencyUs,
				Changes:   it.Changes,
				Analysis:  it.Analysis,
				Correct:   strings.EqualFold(it.Correctness, "PASS"),
			}
			if insight.Correct && insight.Speedup > 1.0 {
				successes = append(successes, insight)
			} else if insight.Changes != "" {
				failures = append(failures, insight)
			}
		}
	}

	// Sort successes by speedup descending
	sort.Slice(successes, func(i, j int) bool {
		return successes[i].Speedup > successes[j].Speedup
	})

	// Successful strategies
	b.WriteString("## Strategies That Worked\n\n")
	if len(successes) == 0 {
		b.WriteString("No successful optimization found yet.\n\n")
	} else {
		b.WriteString("| Speedup | Latency | Changes | Why it helped |\n")
		b.WriteString("|---------|---------|---------|---------------|\n")
		shown := 0
		for _, s := range successes {
			if shown >= 15 {
				break
			}
			changes := oneLine(s.Changes, 60)
			analysis := oneLine(s.Analysis, 60)
			latStr := "-"
			if s.Latency > 0 {
				latStr = fmt.Sprintf("%.1f us", s.Latency)
			}
			b.WriteString(fmt.Sprintf("| %.2fx | %s | %s | %s |\n",
				s.Speedup, latStr, changes, analysis))
			shown++
		}
		b.WriteString("\n")
	}

	// Failed/regression strategies
	b.WriteString("## Strategies That Did NOT Work\n\n")
	regressions := filterRegressions(failures)
	if len(regressions) == 0 {
		b.WriteString("No recorded regressions.\n\n")
	} else {
		b.WriteString("Avoid repeating these approaches unless you have a fundamentally different angle.\n\n")
		b.WriteString("| Result | Changes | Why it failed |\n")
		b.WriteString("|--------|---------|---------------|\n")
		shown := 0
		for _, f := range regressions {
			if shown >= 15 {
				break
			}
			changes := oneLine(f.Changes, 60)
			analysis := oneLine(f.Analysis, 60)
			result := "no improvement"
			if !f.Correct {
				result = "FAIL (incorrect)"
			} else if f.Speedup < 1.0 && f.Speedup > 0 {
				result = fmt.Sprintf("%.2fx (regression)", f.Speedup)
			}
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n", result, changes, analysis))
			shown++
		}
		b.WriteString("\n")
	}

	// Key takeaways
	b.WriteString("## Key Takeaways\n\n")
	takeaways := deriveTakeaways(successes, regressions)
	for _, t := range takeaways {
		b.WriteString(fmt.Sprintf("- %s\n", t))
	}
	if len(takeaways) == 0 {
		b.WriteString("- Not enough data to derive patterns yet.\n")
	}
	b.WriteString("\n")

	// Per-run timeline (compact)
	b.WriteString("## Run Timeline\n\n")
	for _, run := range runs {
		bestInRun := 0.0
		passCount := 0
		for _, it := range run.Iterations {
			if it.SpeedupVsBaseline > bestInRun {
				bestInRun = it.SpeedupVsBaseline
			}
			if strings.EqualFold(it.Correctness, "PASS") {
				passCount++
			}
		}
		b.WriteString(fmt.Sprintf("### %s\n\n", run.RunID))
		b.WriteString(fmt.Sprintf("- Iterations: %d (PASS: %d)\n", len(run.Iterations), passCount))
		b.WriteString(fmt.Sprintf("- Best speedup: %.2fx\n\n", bestInRun))
	}

	return b.String()
}

func filterRegressions(failures []iterationInsight) []iterationInsight {
	var regressions []iterationInsight
	seen := map[string]bool{}
	for _, f := range failures {
		key := oneLine(f.Changes, 80)
		if seen[key] {
			continue
		}
		seen[key] = true
		regressions = append(regressions, f)
	}
	return regressions
}

func deriveTakeaways(successes []iterationInsight, regressions []iterationInsight) []string {
	var takeaways []string

	patterns := map[string]int{}
	for _, s := range successes {
		text := strings.ToLower(s.Changes + " " + s.Analysis)
		for _, keyword := range []string{
			"non-persistent", "block_size", "num_warps", "num_stages",
			"vectoriz", "evict", "int32", "int64", "persistent",
			"num_sms", "occupancy", "register", "shared memory",
			"pipeline", "prefetch", "tile", "coalescing",
		} {
			if strings.Contains(text, keyword) {
				patterns[keyword]++
			}
		}
	}

	type kv struct {
		key   string
		count int
	}
	var sorted []kv
	for k, v := range patterns {
		sorted = append(sorted, kv{k, v})
	}
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].count > sorted[j].count })

	for _, p := range sorted {
		if p.count >= 2 {
			takeaways = append(takeaways, fmt.Sprintf(
				"'%s' appeared in %d successful iterations — likely an effective direction.",
				p.key, p.count))
		}
		if len(takeaways) >= 5 {
			break
		}
	}

	failPatterns := map[string]int{}
	for _, f := range regressions {
		text := strings.ToLower(f.Changes + " " + f.Analysis)
		for _, keyword := range []string{
			"evict", "make_block_ptr", "block_ptr", "fp16", "tf32",
		} {
			if strings.Contains(text, keyword) {
				failPatterns[keyword]++
			}
		}
	}
	for k, v := range failPatterns {
		if v >= 2 {
			takeaways = append(takeaways, fmt.Sprintf(
				"'%s' appeared in %d failed attempts — approach with caution.",
				k, v))
		}
	}

	return takeaways
}

func oneLine(s string, maxLen int) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", "")
	s = strings.ReplaceAll(s, "|", "/")
	s = strings.TrimSpace(s)
	if len(s) > maxLen {
		s = s[:maxLen-3] + "..."
	}
	return s
}

func countIterations(runs []RunRecord) int {
	n := 0
	for _, r := range runs {
		n += len(r.Iterations)
	}
	return n
}
