#!/usr/bin/env python3
"""
init_kernel.py -- Generate kernel.py + reference.py from a kernel.yaml spec.

Usage:
    python scripts/init_kernel.py <pkg_dir>
    python scripts/init_kernel.py workspace/kernel_assets/rms_norm_pkg

The <pkg_dir> must contain a kernel.yaml file describing the kernel.
See templates/kernel.yaml.example for the schema.

Generated files:
    kernel.py     -- Model class wrapping the user's kernel + get_inputs()
    reference.py  -- Golden reference skeleton + get_inputs()
"""

from __future__ import annotations

import argparse
import os
import sys
import textwrap
from pathlib import Path

import yaml

# -- dtype mapping ----------------------------------------------------------

DTYPE_MAP = {
    "bf16": "torch.bfloat16",
    "bfloat16": "torch.bfloat16",
    "fp16": "torch.float16",
    "float16": "torch.float16",
    "fp32": "torch.float32",
    "float32": "torch.float32",
    "fp64": "torch.float64",
    "float64": "torch.float64",
    "int32": "torch.int32",
    "int64": "torch.int64",
    "bool": "torch.bool",
    "fp8": "torch.float8_e4m3fn",
    "float8": "torch.float8_e4m3fn",
}


def resolve_dtype(raw: str) -> str:
    key = raw.strip().lower()
    if key not in DTYPE_MAP:
        print(f"  WARNING: unknown dtype '{raw}', using torch.float32", file=sys.stderr)
        return "torch.float32"
    return DTYPE_MAP[key]


# -- YAML loading & validation ----------------------------------------------

def load_spec(yaml_path: Path) -> dict:
    with open(yaml_path) as f:
        spec = yaml.safe_load(f)

    errors = []
    if not spec.get("name"):
        errors.append("'name' is required")
    if spec.get("backend") not in ("triton", "cuda"):
        errors.append("'backend' must be 'triton' or 'cuda'")
    if not spec.get("dims"):
        errors.append("'dims' is required (e.g. dims: {M: 8192, N: 2048})")
    if not spec.get("inputs"):
        errors.append("'inputs' is required (list of {name, dtype, shape})")
    else:
        for i, inp in enumerate(spec["inputs"]):
            for field in ("name", "dtype", "shape"):
                if field not in inp:
                    errors.append(f"inputs[{i}] missing '{field}'")

    if errors:
        print(f"ERROR: kernel.yaml validation failed:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        sys.exit(1)

    return spec


# -- input tensor construction ----------------------------------------------

def build_tensor_expr(inp: dict, dim_names: set[str], use_locals: bool = False) -> str:
    """Build a torch.randn(...) expression for one input.

    use_locals: if True, dimension names are lowercased (for reference.py where
    local variables shadow module-level globals to support SHAPE_CONFIGS override).
    """
    name = inp["name"]
    dtype = resolve_dtype(inp["dtype"])
    shape_parts = inp["shape"]
    if isinstance(shape_parts, str):
        shape_parts = [s.strip() for s in shape_parts.split(",")]

    def dim_ref(s):
        upper = str(s).upper()
        if upper in dim_names:
            return upper.lower() if use_locals else upper
        return str(s)

    shape_expr = ", ".join(dim_ref(s) for s in shape_parts)

    factory = "torch.randn"
    if "int" in dtype:
        factory = f"torch.randint(0, 100, ({shape_expr},), dtype={dtype}, device=\"cuda\")"
        return f"    {name} = {factory}"
    if "bool" in dtype:
        return f"    {name} = torch.randint(0, 2, ({shape_expr},), dtype={dtype}, device=\"cuda\")"

    return f"    {name} = {factory}({shape_expr}, dtype={dtype}, device=\"cuda\")"


# -- reference.py generation ------------------------------------------------

def generate_reference(spec: dict) -> str:
    dims = spec["dims"]
    inputs = spec["inputs"]
    name = spec["name"]

    # dim declarations
    dim_lines = []
    for k, v in dims.items():
        dim_lines.append(f"{k.upper()} = {v}")
    dim_block = "\n".join(dim_lines)

    # forward args
    forward_args = ", ".join(
        f"{inp['name']}: torch.Tensor" for inp in inputs
    )

    # get_inputs body
    dim_names = {k.upper() for k in dims}
    local_assigns = ", ".join(k.lower() for k in dims)
    global_assigns = ", ".join(k.upper() for k in dims)
    tensor_lines = []
    for inp in inputs:
        tensor_lines.append(build_tensor_expr(inp, dim_names, use_locals=True))
    return_names = ", ".join(inp["name"] for inp in inputs)

    shape_config_dims = ", ".join(f'"{k.upper()}": {v}' for k, v in dims.items())

    return f'''\
"""
reference.py -- Golden reference for {name}.
Auto-generated by: scripts/init_kernel.py
"""

import torch
import torch.nn as nn


class Model(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, {forward_args}) -> torch.Tensor:
        # TODO: implement the pure-PyTorch reference computation
        raise NotImplementedError("fill in the golden reference for {name}")


{dim_block}


SHAPE_CONFIGS = [
    {{"label": "default", {shape_config_dims}}},
]


def get_inputs(shape_idx=None):
    {local_assigns} = {global_assigns}
    if shape_idx is not None and 0 <= shape_idx < len(SHAPE_CONFIGS):
        cfg = SHAPE_CONFIGS[shape_idx]
        {"; ".join(f'{k.lower()} = cfg["{k.upper()}"]' for k in dims)}
{chr(10).join(tensor_lines)}
    return [{return_names}]


def get_init_inputs():
    return []
'''


# -- kernel.py generation (Triton) ------------------------------------------

def generate_triton_kernel(spec: dict, source_content: str | None) -> str:
    dims = spec["dims"]
    inputs = spec["inputs"]
    name = spec["name"]

    # forward args
    forward_args = ", ".join(
        f"{inp['name']}: torch.Tensor" for inp in inputs
    )

    # get_inputs
    dim_names = {k.upper() for k in dims}
    dim_lines = "\n".join(f"{k.upper()} = {v}" for k, v in dims.items())
    local_assigns = ", ".join(k.lower() for k in dims)
    global_assigns = ", ".join(k.upper() for k in dims)
    tensor_lines = []
    for inp in inputs:
        tensor_lines.append(build_tensor_expr(inp, dim_names))
    return_names = ", ".join(inp["name"] for inp in inputs)

    if source_content is not None:
        kernel_block = source_content.rstrip()
    else:
        kernel_block = textwrap.dedent(f"""\
            import triton
            import triton.language as tl


            @triton.jit
            def _{name}_kernel():
                # TODO: implement the Triton kernel
                pass""")

    # Check if source already has Model class
    if "class Model" in kernel_block:
        # Source is already a complete kernel.py; use it as-is but ensure
        # get_inputs has shape support
        result = kernel_block
        if "get_inputs" not in result:
            result += f"""


{dim_lines}


def get_inputs():
{chr(10).join(tensor_lines)}
    return [{return_names}]


def get_init_inputs():
    return []
"""
        return result

    return f'''\
"""
kernel.py -- Optimizable kernel for {name}.
Auto-generated by: scripts/init_kernel.py
"""

import torch
import torch.nn as nn
{kernel_block}


class Model(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, {forward_args}) -> torch.Tensor:
        # TODO: call the Triton kernel and return the result
        raise NotImplementedError("wire up the kernel launch for {name}")


{dim_lines}


def get_inputs():
{chr(10).join(tensor_lines)}
    return [{return_names}]


def get_init_inputs():
    return []
'''


# -- kernel.py generation (CUDA C) ------------------------------------------

def generate_cuda_kernel(spec: dict, source_content: str | None) -> str:
    dims = spec["dims"]
    inputs = spec["inputs"]
    name = spec["name"]
    cuda_opts = spec.get("cuda", {})

    forward_args = ", ".join(
        f"{inp['name']}: torch.Tensor" for inp in inputs
    )

    dim_names = {k.upper() for k in dims}
    dim_lines = "\n".join(f"{k.upper()} = {v}" for k, v in dims.items())
    tensor_lines = []
    for inp in inputs:
        tensor_lines.append(build_tensor_expr(inp, dim_names))
    return_names = ", ".join(inp["name"] for inp in inputs)

    # cuda_source content
    if source_content is not None:
        cuda_src_content = source_content.rstrip()
    else:
        cuda_src_content = textwrap.dedent(f"""\
            #include <torch/extension.h>
            #include <ATen/cuda/CUDAContext.h>
            #include <cuda_runtime.h>

            // TODO: implement the CUDA kernel for {name}

            torch::Tensor {name}_cuda(/* args */) {{
                // TODO: implement host wrapper
                return torch::Tensor();
            }}""")

    # escape backslashes and quotes for embedding in Python string
    cuda_src_escaped = cuda_src_content.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')

    extra_include = ""
    include_paths = cuda_opts.get("extra_include_paths", [])
    if include_paths:
        paths_str = ", ".join(f'"{p}"' for p in include_paths)
        extra_include = f"\n    extra_include_paths=[{paths_str}],"

    extra_cflags = cuda_opts.get("extra_cuda_cflags", ["-O3", "-std=c++17"])
    cflags_str = ", ".join(f'"{f}"' for f in extra_cflags)

    cpp_func_name = f"{name}_cuda"
    cpp_source_hint = f'torch::Tensor {cpp_func_name}(/* match your CUDA wrapper signature */);'

    return f'''\
"""
kernel.py -- CUDA C kernel for {name}.
Auto-generated by: scripts/init_kernel.py
"""

import torch
import torch.nn as nn
from torch.utils.cpp_extension import load_inline

cuda_source = r"""
{cuda_src_content}
"""

cpp_source = "{cpp_source_hint}"

module = load_inline(
    name="{name}",
    cpp_sources=cpp_source,
    cuda_sources=cuda_source,
    functions=["{cpp_func_name}"],{extra_include}
    extra_cuda_cflags=[{cflags_str}],
    verbose=True,
)


class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.custom_op = module

    def forward(self, {forward_args}) -> torch.Tensor:
        # TODO: call self.custom_op.{cpp_func_name}(...) and return the result
        raise NotImplementedError("wire up the CUDA kernel call for {name}")


{dim_lines}


def get_inputs():
{chr(10).join(tensor_lines)}
    return [{return_names}]


def get_init_inputs():
    return []
'''


# -- syntax verification ----------------------------------------------------

def verify_syntax(path: Path) -> bool:
    try:
        source = path.read_text()
        compile(source, str(path), "exec")
        return True
    except SyntaxError as e:
        print(f"  SYNTAX ERROR in {path.name}: {e}", file=sys.stderr)
        return False


# -- main -------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate kernel.py + reference.py from kernel.yaml",
        epilog="See templates/kernel.yaml.example for the YAML schema.",
    )
    parser.add_argument("pkg_dir", help="Path to the kernel package directory (must contain kernel.yaml)")
    parser.add_argument("--force", action="store_true", help="Overwrite existing kernel.py / reference.py")
    parser.add_argument("--dry-run", action="store_true", help="Print generated files without writing")
    args = parser.parse_args()

    pkg_dir = Path(args.pkg_dir)
    yaml_path = pkg_dir / "kernel.yaml"
    if not yaml_path.exists():
        print(f"ERROR: {yaml_path} not found", file=sys.stderr)
        print(f"Create a kernel.yaml in {pkg_dir}. See templates/kernel.yaml.example for the schema.", file=sys.stderr)
        sys.exit(1)

    spec = load_spec(yaml_path)
    name = spec["name"]
    backend = spec["backend"]

    print(f"[init-kernel] {name} (backend={backend})")

    # Load user-provided kernel source if specified
    source_content = None
    if spec.get("kernel_source"):
        src_path = pkg_dir / spec["kernel_source"]
        if not src_path.exists():
            print(f"ERROR: kernel_source '{spec['kernel_source']}' not found in {pkg_dir}", file=sys.stderr)
            sys.exit(1)
        source_content = src_path.read_text()
        print(f"  loaded source: {src_path.name} ({len(source_content)} bytes)")

    # Generate kernel.py
    if backend == "triton":
        kernel_content = generate_triton_kernel(spec, source_content)
    else:
        kernel_content = generate_cuda_kernel(spec, source_content)

    # Load user-provided reference source if specified
    ref_source = None
    if spec.get("reference_source"):
        ref_path = pkg_dir / spec["reference_source"]
        if ref_path.exists():
            ref_source = ref_path.read_text()
            print(f"  loaded reference: {ref_path.name} ({len(ref_source)} bytes)")

    # Generate reference.py
    if ref_source and "class Model" in ref_source:
        reference_content = ref_source
    else:
        reference_content = generate_reference(spec)

    # Output
    kernel_out = pkg_dir / "kernel.py"
    ref_out = pkg_dir / "reference.py"

    if args.dry_run:
        print(f"\n{'='*60}")
        print(f"  kernel.py ({len(kernel_content)} bytes)")
        print(f"{'='*60}")
        print(kernel_content)
        print(f"\n{'='*60}")
        print(f"  reference.py ({len(reference_content)} bytes)")
        print(f"{'='*60}")
        print(reference_content)
        return

    for path, content, label in [
        (kernel_out, kernel_content, "kernel.py"),
        (ref_out, reference_content, "reference.py"),
    ]:
        if path.exists() and not args.force:
            print(f"  SKIP {label} (already exists, use --force to overwrite)")
            continue
        path.write_text(content)
        print(f"  wrote {label} ({len(content)} bytes)")

    # Syntax check
    print()
    all_ok = True
    for path in [kernel_out, ref_out]:
        if path.exists():
            if verify_syntax(path):
                print(f"  OK {path.name} syntax valid")
            else:
                all_ok = False

    # Report what needs manual work
    print()
    todos = []
    if kernel_out.exists():
        content = kernel_out.read_text()
        if "NotImplementedError" in content or "# TODO" in content:
            todos.append(f"  - {kernel_out.name}: fill in the kernel launch logic in Model.forward()")
    if ref_out.exists():
        content = ref_out.read_text()
        if "NotImplementedError" in content:
            todos.append(f"  - {ref_out.name}: fill in the golden reference in Model.forward()")

    if todos:
        print("TODO (fill in before running optimization):")
        for t in todos:
            print(t)
    else:
        print("Both files are complete. Ready for `kernelhub prepare`.")

    if not all_ok:
        sys.exit(1)


if __name__ == "__main__":
    main()
